//
//  MenloworksEventsConstants.swift
//  Depo_LifeTech
//
//  Created by Raman Harhun on 2/23/18.
//  Copyright © 2018 LifeTech. All rights reserved.
//

struct MenloworksEventsConstants {
    private init() {}
    static let firstsession = "Firstsession"
    static let newsession = "Newsession"
    static let signupCompleted = "Signup_completed"
    static let loggedinCompleted = "loggedin"
    static let firstAutosyncOFF = "first_autosyncoff"
    static let autosyncOFF = "autosyncoff"
    static let allFilesOpen = "all_files"
    static let photosAndVideosOpen = "photos_and_videos"
    static let musicOpen = "music"
    static let documentsOpen = "documents"
    static let contactSyncPageOpen = "contact_sync_page"
    static let contactDownloaded = "contact_downloaded"
    static let contactUploaded = "contact_uploaded"
    static let favoritesOpen = "favs"
    static let storyPageOpen = "story_page"
    static let storyCreated = "story_created"
    static let packagesOpen = "packages"
    static let preferencesOpen = "preferences"
    static let fiftyGBClicked = "50_gb_button_clicked"
    static let fiveHundredGBClicked = "500_gb_button_clicked"
    static let twoThousandFiveHundredGBClicked = "2_5_tb_button_clicked"
    static let fileDeleted = "deleted"
    static let promocodeActivated = "promocode_activated"
    static let socialMediaPageOpen = "social_media"
    static let instagramConnected = "instagram_done"
    static let facebookConnected = "facebook_done"
    static let loggedOut = "logged_out"
    static let faceImageRecognitionOn = "face_image_recognition_on"
    static let faceImageRecognitionOff = "face_image_recognition_off"
    static let passcodeSet = "passcode_set"
    static let touchIDSet = "touchid"
    static let turkcellPasswordSet = "turkcellpassword"
    static let autoLoginSet = "autologin"
    static let removeFromAlbumClicked = "removeFromAlbum_button_clicked"
    static let cellographClicked = "cellograph_button_clicked"
    static let syncClicked = "sync_button_clicked"
    static let downloadClicked = "download_button_clicked"
    static let deleteClicked = "delete_button_clicked"
    static let shareClicked = "share_button_clicked"
    static let addToFavoritesClicked = "add_to_favorites_button_clicked"
    static let apporvedEulaPage = "EulaPage"
    static let emailChanged = "EmailEntry"
    static let facebookTransfered = "facebook_transfer"
    static let instagramTransfered = "instagram_transfer"
    static let dropboxTransfered = "dropbox_transfer"
    static let deviceStorageExceeded80Perc = "device_storage_exceeded_80_perc"
    static let deviceStorageExceeded90Perc = "device_storage_exceeded_90_perc"
    static let quotaExceeded80PercStatus = "quota_exceeded_80_perc"
    static let quotaExceeded90PercStatus = "quota_exceeded_90_perc"
    static let quotaFullStatus = "quota_full"
    static let fiftyGBPurchasedStatus = "Satınalındı50GB"
    static let fiveHundredGBPurchasedStatus = "Satınalındı500GB"
    static let twoThousandFiveHundredGBPurchasedStatus = "Satınalındı25TB"
    static let downloadedItemFormat = "Download>%@"
    static let sharedItemFormat = "Share>%@>%@"
    static let profileNameEmpty = "profile_name_empty"
    static let profileNameFull = "profile_name_full"
    static let backgroundSync = "BackgroundSync"
    static let photopickAnalyzeDone = "photopick_analyze_done"
}
