platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

def core_pods
 	pod 'Fabric'
    pod 'Crashlytics'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    
    pod 'SDWebImage'
    pod 'GoogleConversionTracking'
    pod 'Adjust'
    #pod 'ActiveLabel'

    #Keyboard
    pod 'Typist'

    pod 'ObjectiveDropboxOfficial'


    pod 'SimpleExif'
    pod 'XYPieChart'
    pod 'CircleProgressBar', '~> 0.32'
    pod 'UIImage-Categories'
    pod 'iCarousel'
    pod 'SplunkMint'
    
    # json
    pod 'SwiftyJSON', '~>3'
    pod 'ReachabilitySwift'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'ExpandableTableViewController'

end

target 'Depo_LifeTech' do

	core_pods

#  target 'DepoTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

end

target ‘TC_Depo_LifeTech’ do
	core_pods
end
