platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!
ENV['COCOAPODS_DISABLE_STATS'] = "true"

def shared_pods
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON', '~>3'
  pod 'KeychainSwift', '~> 11.0'
end

def core_pods
  shared_pods
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  pod 'SDWebImage'
  pod 'GoogleConversionTracking'
  pod 'Firebase/Core'
  pod 'GoogleTagManager'
  pod 'Adjust'
  #pod 'ActiveLabel'


  #Keyboard
  pod 'Typist', '~> 1.1.0'

  pod 'ObjectiveDropboxOfficial'


  pod 'SimpleExif', :git => 'https://github.com/bonyadmitr/SimpleExif.git'
  pod 'XYPieChart'
  pod 'CircleProgressBar', '~> 0.32'
  pod 'UIImage-Categories'
  pod 'iCarousel'

  pod 'ReachabilitySwift'
  pod 'MBProgressHUD', '~> 1.1.0'

  #logger
  pod 'XCGLogger', '~> 6.0'

  #widget
  pod 'MMWormhole', '~> 2.0.0'
  
  #migration
  pod 'SQLite.swift', '0.11.4'
  
  pod 'MetalPetal', '~> 1.0'
  pod 'GPUImage'

end

target 'Depo_LifeTech' do
	core_pods
end

target 'LifeboxShared' do
    shared_pods
    pod 'MMWormhole', '~> 2.0.0'
end

target 'LifeboxFileProvider' do
    shared_pods
    pod 'MMWormhole', '~> 2.0.0'
end

target 'LifeboxFileProviderUI' do
    shared_pods
end

target 'autosync-widget' do
    pod 'MMWormhole', '~> 2.0.0'
end

target 'TC_Depo_LifeTech' do
	core_pods
end

target 'LifeboxUnitTests' do
	core_pods
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['XCGLogger', 'netfox'].include? "#{target}"
            print "Setting #{target}'s SWIFT_VERSION to 4.0\n"
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
            else
            target.build_configurations.each do |config|
                config.build_settings.delete('SWIFT_VERSION')
            end
        end
    end

    print "Setting the default SWIFT_VERSION to 3.0\n"
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
        config.build_settings['ENABLE_BITCODE'] = 'YES'
    end

    ## https://stackoverflow.com/a/32652721/5893286
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
