source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!
ENV['COCOAPODS_DISABLE_STATS'] = "true"
ENV['SWIFT_VERSION'] = '5'


def shared_pods
  #pod 'Alamofire', '~> 4.8.1'
  #pod 'SwiftyJSON', '~> 5'
  pod 'KeychainSwift', '~> 19'
end

def core_pods
  shared_pods
  pod 'Firebase/Core', '~> 7'
  pod 'Firebase/Crashlytics', '~> 7'
  pod 'FirebaseAnalytics', '~> 7'
  pod 'Firebase/RemoteConfig', '~> 7'
  pod 'Firebase/DynamicLinks', '~> 7'
  pod 'Firebase/Auth', '~> 7'
  pod 'GoogleSignIn'
  pod 'AGConnectCore'
  pod 'AGConnectAppLinking'

  pod 'Netmera', '~> 3.16.0'

  pod 'SDWebImage', '~> 4'
  pod 'GoogleConversionTracking', '~> 3'
  pod 'GoogleTagManager', '~> 7'
  pod 'Adjust', '~> 4.35.2'
  pod 'SNCollectionViewLayout'
  #pod 'ActiveLabel'

  #Keyboard
  pod 'Typist', '~> 1'
  pod 'iCarousel', '~> 1'
  pod 'IQKeyboardManagerSwift'

  pod 'ReachabilitySwift'
  pod 'MBProgressHUD', '~> 1'
  pod 'TTGSnackbar', '~> 1'
  
  #logger
  #pod 'XCGLogger', '~> 7'

  #widget
  pod 'MMWormhole', '~> 2.0.0'
  
  #migration
  pod 'SQLite.swift', '0.12.0'
  
  pod 'SwiftyGif', '~> 5'
end

def lifebox_pods
  core_pods
  pod 'FBSDKCoreKit', '~> 8'
  pod 'FBSDKLoginKit', '~> 8'
  pod 'FBSDKShareKit', '~> 8'
  pod 'YYImage', '~> 1'
  pod 'SwiftyDropbox', '~> 6'
  pod 'MaterialComponents/Slider'
  pod 'Mantis', :git => 'https://github.com/fireengine-ios/Mantis.git', :tag => 'FE-1.3.2.5'
  pod 'MetalPetal/Swift', '=1.15.0'
end

def sharing_pods
  shared_pods
  pod 'Netmera', '~> 3.16.0'
  pod 'MMWormhole', '~> 2.0.0'
end

def file_provider_pods
  shared_pods
  pod 'Netmera', '~> 3.16.0'
  pod 'MMWormhole', '~> 2.0.0'
end

def file_provider_ui_pods
  shared_pods
end

def notification_pods
  pod 'Netmera', '~> 3.16.0'
  pod 'iCarousel', '~> 1'
end

def widget_pods
  shared_pods
  pod 'SDWebImage', '~> 4'
  pod 'MMWormhole', '~> 2.0.0'
#  pod 'XCGLogger', '~> 7'
end

target 'Lifebox' do
  lifebox_pods
end

target 'Lifebox_Friendly' do
  lifebox_pods
end

target 'LifeboxShared' do
  sharing_pods
end

target 'LifeboxFileProvider' do
  file_provider_pods
end

target 'LifeboxFileProviderUI' do
  file_provider_ui_pods
end

target 'LifeboxWidgetExtension' do
  widget_pods
end

target 'LifeboxUnitTests' do
  lifebox_pods
end

target 'LifeboxNotificationServiceExtension' do
 pod "Netmera/NotificationServiceExtension"
end

post_install do |installer|
    ## https://stackoverflow.com/a/32652721/5893286
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end
end
