//
//  MenloworksTagsConstants.swift
//  Depo_LifeTech
//
//  Created by Raman Harhun on 2/23/18.
//  Copyright © 2018 LifeTech. All rights reserved.
//

extension MenloworksTags {
    class NameConstants {
        static let tutorial = "tutorial"
        static let musicUpload = "music_uploaded"
        static let fileUpload = "file_uploaded"
        static let wifi3g = "wifi/3g"
        static let loggedIn = "logged_in"
        static let loginCompleted = "logincompleted"
        static let signupCompleted = "signupcompleted"
        static let faceImageRecognitionStatus = "face_image_recognition"
        static let instagramImportStatus = "instagram_import"
        static let facebookImportStatus = "facebook_import"
        static let passcodeStatus = "passcode_set"
        static let touchIDStatus = "touchid_set"
//        static let turckcellPasswordStatus = "turkcell_password"
//        static let autologinStatus = "auto_login"
        static let firstsession = "Firstsession"
        static let search = "search"
        static let favoritesClicked = "add_to_favorites_button_clicked"
        static let shareClicked = "share_button_clicked"
        static let deleteClicked = "delete_button_clicked"
        static let downloadClicked = "download_button_clicked"
        static let syncClicked = "sync_button_clicked"
        static let cellographClicked = "cellograph_button_clicked"
        static let removeFromAlbumClicked = "removeFromAlbum_button_clicked"
        static let storyCreated = "story_created"
        static let videoDisplayed = "video_displayed"
        static let photoEdit = "photo_edit"
        static let contactDownloaded = "contact_downloaded"
        static let contactUploaded = "contact_uploaded"
        static let autoSyncVideosViaWifi = "autosyncvideoswifi"
        static let autoSyncVideosOff = "autosyncvideosoff"
        static let autoSyncVideosViaLte = "autosyncvideoslte"
        static let autoSyncPhotosViaWifi = "autosyncphotoswifi"
        static let autoSyncPhotosOff = "autosyncphotosoff"
        static let autoSyncPhotosViaLte = "autosyncphotoslte"
        static let firstAutoSyncVideosViaWifi = "first_autosyncwifiVideos"
        static let firstAutoSyncVideosViaLte = "first_autosynclteVideos"
        static let firstAutoSyncVideosOff = "first_autosyncoffVideos"
        static let firstAutoSyncPhotosViaWifi = "first_autosyncwifiPhotos"
        static let firstAutoSyncPhotosViaLte = "first_autosyncltePhotos"
        static let firstAutoSyncPhotosOff = "first_autosyncoffPhotos"
        static let autoSyncOff = "autosyncoff"
        static let packagesOpen = "packages"
        static let preferencesOpen = "preferences"
        static let storyPageOpen = "story_page"
        static let contactSyncPageOpen = "contact_sync_page"
        static let musicOpen = "music"
        static let documentsOpen = "documents"
        static let photosAndVideosOpen = "photos_and_videos"
        static let allFilesOpen = "all_files"
        static let instagramConnected = "instagram_done"
        static let facebookConnected = "facebook_done"
        static let promocodeActivated = "promocode_activated"
        static let fiftyGBClicked = "50_gb_button_clicked"
        static let fiveHundredGBClicked = "500_gb_button_clicked"
        static let twoThousandFiveHundredGBClicked = "2_5_tb_button_clicked"
        static let userPackage = "user_package"
        static let noUserPackage = "no_package"
        static let autoLoginChanged = "auto_login"
        static let turkcellPasswordChanged = "turkcell_password"
        static let platinUserStatus = "platin_user"
        static let notificationsPermissionStatus = "notification_permission"
        static let galleryPermissionStatus = "gallery_permission"
        static let locationPermissionStatus = "location_permission"
        static let fileDeleted = "deleted"
        static let quotaStatus = "quota_status"
        static let autosyncStatus = "autosync"
        static let firstAutoSyncOff = "first_autosyncoff"
        static let autosyncPhotosStatus = "autosyncPhotos"
        static let autosyncVideosStatus = "autosyncVideos"
        static let fiftyGBPurchasedStatus = "Satınalındı50GB"
        static let fiveHundredGBPurchasedStatus = "Satınalındı500GB"
        static let twoThousandFiveHundredGBPurchasedStatus = "Satınalındı25TB"
        static let favoritesPageClicked = "favs"
        static let socialMediaPageClicked = "social_media"
        static let periodicContactSync = "periodic_contact_sync"
        static let editedPhotoSave = "photo_edit_save"
        
        static let photoUploadAutosync = "photo_upload_autosync"
        static let photoUploadManual = "photo_upload_manual"
        static let photoUploadBackground = "photo_upload_background"
        
        static let videoUploadAutosync = "video_uploaded_autosync"
        static let videoUploadManual = "video_upload_manual"
        static let videoUploadBackground = "video_upload_background"
        
        static let profileNameEmpty = "profile_name_empty"
        static let profileNameFull = "profile_name_full"
        static let profileName = "profile_name"
        
        static let photopickLeftAnalysis = "photopick_left_analysis"
        static let photopickAnalyze = "photopick_analyze"
        static let photopickAnalyzeSuccess = "photopick_analyze_success"
        static let photopickAnalyzeFail = "photopick_analyze_fail"
        static let photopickDailyDrawLeft = "daily_draw_left"
        static let photopickTotalDraw = "total_draw"
    }
    
    class ValueConstants {
        static let mobile = "mobile"
        static let wifi = "wifi"
        static let lte = "lte"
        static let `true` = "true"
        static let `false` = "false"
        static let yes = "yes"
        static let no = "no"
        static let on = "on"
        static let off = "off"
        static let granted = "granted"
        static let denied = "denied"
        static let free = "FREE"
        static let success = "Success"
        static let fail = "Fail"
    }
}
